### PR TITLE
Support web browsers for any systema that help supports.

### PR DESCRIPTION
**Pull request by equwal**
Just use the `open` function, so you can support non-mac users.

### CODE REVIEW

**Comment by patrickf3139** [comment]
Hey @equwal , so sorry I missed this. I'm ready to approve and merge but there seems to an extraneous file, namely open_browser. It doesn't get used anywhere.

**Comment by patrickf3139** [comment]
Hey Spenser, don't know if you still use fish or my plugin, but since this has been open for so long, I feel bad so I'm made a couple modifications and am going to merge. Feel free to open up another PR if this doesn't suit you! Thank you so much for using my plugin and submitting a PR :)

**Comment by equwal** [comment]
> Hey Spenser, don't know if you still use fish or my plugin, but since this has been open for so long, I feel bad so I'm made a couple modifications and am going to merge. Feel free to open up another PR if this doesn't suit you! Thank you so much for using my plugin and submitting a PR :)

I no longer use your plugin, but I definitely agree with removing windows support. What a waste of time!

**Comment by patrickf3139** [comment]
Wow interesting. I never considered how difficult it must be to make fish compatible on Windows. Well, I appreciate you making that effort a long time ago!

**Pull request merged**
